In [6]:
#write a function to read the motif segments from the pdb file
import os
from Bio.PDB import PDBParser
def read_motif_segments(pdb_file):
    #read the pdb file
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure('5YUI', pdb_file)
    return structure

structure = read_motif_segments("/home/pc/Documents/protein_design/twisted_diffusion_sampler/protein_exp/motif_scaffolding/targets/5YUI_motif.pdb")

In [7]:
#leave c-alpha atoms only
ca_atoms = [atom for atom in structure.get_atoms() if atom.get_name() == 'CA']


In [9]:
#partition into 5, 3, 3
motif_segments = {}
motif_segments['motif_1'] = ca_atoms[:5]
motif_segments['motif_2'] = ca_atoms[5:8]
motif_segments['motif_3'] = ca_atoms[8:]

In [19]:
#get coordinates of the motifs
motif_coords = {}
motif_coords['motif_1'] = [atom.get_coord() for atom in motif_segments['motif_1']]
motif_coords['motif_2'] = [atom.get_coord() for atom in motif_segments['motif_2']]
motif_coords['motif_3'] = [atom.get_coord() for atom in motif_segments['motif_3']]


In [20]:
motif_coords['motif_3']

[array([6.737, 4.407, 3.971], dtype=float32),
 array([7.74 , 0.842, 3.056], dtype=float32),
 array([9.981, 1.956, 0.169], dtype=float32)]

In [21]:
#find the central locations of the motifs
import numpy as np
#def a translation matrix to make their centers of mass at the origin
def center_coordinates(coords):
    """
    Center a list of 3D coordinates by subtracting the mean.
    
    Parameters:
    coords: numpy array of shape (N, 3) or list of [x, y, z] coordinates
    
    Returns:
    numpy array of centered coordinates with same shape as input
    """
    # Convert to numpy array if input is a list
    coords = np.array(coords)
    
    # Calculate mean along each axis
    center = np.mean(coords, axis=0)
    
    # Subtract mean from all points
    centered_coords = coords - center
    
    return centered_coords

center_coordinates(motif_coords['motif_3'])

array([[-1.415667  ,  2.0053334 ,  1.5723333 ],
       [-0.41266727, -1.5596666 ,  0.6573334 ],
       [ 1.8283329 , -0.44566667, -2.2296667 ]], dtype=float32)